# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ArKlsXOBVMgyC451ACuMUU4sgaJfWgu
"""

from google.colab import drive
drive.mount('/content/drive')
!ls /content/drive/MyDrive

ZIP_PATH_1 = "/content/drive/MyDrive/train_dataset-20260311T052955Z-1-001.zip"
ZIP_PATH_2 = "/content/drive/MyDrive/train_dataset-20260311T052955Z-1-002.zip"

import os

drive_path = "/content/drive/MyDrive"

files = os.listdir(drive_path)

print("Files in Google Drive:")
for f in files:
    print(f)

import json
import os

LABEL_PATH = "/content/train_dataset/gcp_marks.json"

with open(LABEL_PATH, "r") as f:
    labels = json.load(f)

print("Total labeled samples:", len(labels))
first_key = list(labels.keys())[0]

print("Image path:", first_key)
print("Annotation:", labels[first_key])

import cv2
import matplotlib.pyplot as plt

DATASET_PATH = "/content/train_dataset"
image_path = os.path.join(DATASET_PATH, first_key)

img = cv2.imread(image_path)

print("Image shape:", img.shape)

plt.figure(figsize=(10,6))

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Sample GCP Image")
plt.axis("off")

plt.show()

x = labels[first_key]["mark"]["x"]
y = labels[first_key]["mark"]["y"]

plt.figure(figsize=(10,6))

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.scatter(x, y, c='red', s=100)

plt.title("Marker Center")
plt.axis("off")

plt.show()

crop_size = 400

x = int(labels[first_key]["mark"]["x"])
y = int(labels[first_key]["mark"]["y"])

crop = img[
    y-crop_size:y+crop_size,
    x-crop_size:x+crop_size
]

plt.figure(figsize=(6,6))
plt.imshow(cv2.cvtColor(crop, cv2.COLOR_BGR2RGB))

# draw center point inside crop
plt.scatter(crop_size, crop_size, c="red", s=100)

plt.title("Marker Region With Center")
plt.axis("off")
plt.show()

crop_size = 80

x = int(labels[first_key]["mark"]["x"])
y = int(labels[first_key]["mark"]["y"])

crop = img[
    y-crop_size:y+crop_size,
    x-crop_size:x+crop_size
]

plt.figure(figsize=(5,5))
plt.imshow(cv2.cvtColor(crop, cv2.COLOR_BGR2RGB))
plt.scatter(crop_size, crop_size, c="red", s=80)

plt.title("Very Tight Marker Crop")
plt.axis("off")
plt.show()

from collections import Counter

shapes = []
for k in labels:
    if "verified_shape" in labels[k]:
        shapes.append(labels[k]["verified_shape"])

class_counts = Counter(shapes)

print("Class distribution:")
for k, v in class_counts.items():
    print(k, ":", v)

import matplotlib.pyplot as plt

xs = [labels[k]["mark"]["x"] for k in labels]
ys = [labels[k]["mark"]["y"] for k in labels]

plt.figure(figsize=(6,6))
plt.scatter(xs, ys, s=10)
plt.title("Marker Position Distribution")
plt.xlabel("X coordinate")
plt.ylabel("Y coordinate")
plt.show()

missing_images = []

for k in labels:
    path = os.path.join(DATASET_PATH, k)
    if not os.path.exists(path):
        missing_images.append(k)

print("Missing images:", len(missing_images))

!ls /content/train_dataset | head

!ls /content/train_dataset | wc -l

missing_images = []

for k in labels:
    path = os.path.join(DATASET_PATH, k)

    if not os.path.isfile(path):
        missing_images.append(k)

print("Missing images:", len(missing_images))

print("Example missing paths:")
print(missing_images[:5])

!ls "/content/train_dataset/scout_966/a7ee1866bbb652c2d0b92546/GCP53"

!ls /content/drive/MyDrive | grep train_dataset

!rm -rf /content/train_dataset

!unzip "/content/drive/MyDrive/train_dataset-20260311T052955Z-1-001.zip" -d /content

missing_images = []

for k in labels:
    path = os.path.join(DATASET_PATH, k)
    if not os.path.isfile(path):
        missing_images.append(k)

print("Missing images:", len(missing_images))

!ls "/content/drive/MyDrive" | grep train_dataset

!rm -rf /content/train_dataset

!unzip "/content/drive/MyDrive/train_dataset-20260311T052955Z-1-001.zip" -d /content

!unzip "/content/drive/MyDrive/train_dataset-20260311T052955Z-1-002.zip" -d /content

missing_images = []

for k in labels:
    path = os.path.join(DATASET_PATH, k)
    if not os.path.isfile(path):
        missing_images.append(k)

print("Missing images:", len(missing_images))

import random

keys = list(labels.keys())

plt.figure(figsize=(12,12))

for i in range(16):

    k = random.choice(keys)

    path = os.path.join(DATASET_PATH, k)
    img = cv2.imread(path)

    x = int(labels[k]["mark"]["x"])
    y = int(labels[k]["mark"]["y"])

    crop_size = 80
    crop = img[y-crop_size:y+crop_size, x-crop_size:x+crop_size]

    plt.subplot(4,4,i+1)
    plt.imshow(cv2.cvtColor(crop, cv2.COLOR_BGR2RGB))
    plt.title(labels[k]["verified_shape"])
    plt.axis("off")

plt.show()

PATCH_SIZE = 224
HALF = PATCH_SIZE // 2

def extract_patch(img, x, y, patch_size=224):

    half = patch_size // 2

    h, w = img.shape[:2]

    x = int(x)
    y = int(y)

    x1 = max(0, x - half)
    x2 = min(w, x + half)
    y1 = max(0, y - half)
    y2 = min(h, y + half)

    patch = img[y1:y2, x1:x2]

    patch = cv2.resize(patch, (patch_size, patch_size))

    return patch

k = first_key

path = os.path.join(DATASET_PATH, k)

img = cv2.imread(path)

x = labels[k]["mark"]["x"]
y = labels[k]["mark"]["y"]

patch = extract_patch(img, x, y)

plt.imshow(cv2.cvtColor(patch, cv2.COLOR_BGR2RGB))
plt.title(labels[k]["verified_shape"])
plt.axis("off")

plt.figure(figsize=(8,6))

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.scatter(x, y, c='red', s=100)

plt.title(labels[k]["verified_shape"])
plt.axis("off")

print("Key:", k)
print("Label entry:", labels[k])

print("Shape used in plot:", labels[k]["verified_shape"])

shape_to_id = {
    "Cross": 0,
    "Square": 1,
    "L-Shape": 2
}

id_to_shape = {v:k for k,v in shape_to_id.items()}

print(shape_to_id)

import torch
from torch.utils.data import Dataset

class GCPDataset(Dataset):

    def __init__(self, labels, dataset_path, patch_size=224):
        # Filter keys to only include those with 'verified_shape'
        self.keys = [k for k in labels.keys() if "verified_shape" in labels[k]]
        self.labels = labels
        self.dataset_path = dataset_path
        self.patch_size = patch_size

    def __len__(self):
        return len(self.keys)

    def __getitem__(self, idx):

        k = self.keys[idx]

        path = os.path.join(self.dataset_path, k)

        img = cv2.imread(path)

        x = self.labels[k]["mark"]["x"]
        y = self.labels[k]["mark"]["y"]

        patch = extract_patch(img, x, y, self.patch_size)

        patch = cv2.cvtColor(patch, cv2.COLOR_BGR2RGB)

        patch = torch.tensor(patch).permute(2,0,1).float()/255.0

        shape = self.labels[k]["verified_shape"]
        label = shape_to_id[shape]

        return patch, label

dataset = GCPDataset(labels, DATASET_PATH)

print("Dataset size:", len(dataset))

sample_patch, sample_label = dataset[0]

print("Patch shape:", sample_patch.shape)
print("Label:", sample_label)

from torch.utils.data import DataLoader

train_loader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True,
    num_workers=2
)

print("Number of batches:", len(train_loader))

import torchvision.models as models
import torch.nn as nn

model = models.resnet18(pretrained=True)

model.fc = nn.Linear(model.fc.in_features, 3)

print(model)

criterion = nn.CrossEntropyLoss()

import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=0.0003)

print(criterion)
print(optimizer)

from torch.utils.data import random_split

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

print("Train size:", len(train_dataset))
print("Validation size:", len(val_dataset))

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True,
    num_workers=2
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False,
    num_workers=2
)

epochs = 5
best_val_loss = float("inf")

for epoch in range(epochs):

    model.train()
    train_loss = 0

    for patches, labels_batch in train_loader:

        patches = patches.to(device)
        labels_batch = labels_batch.to(device)

        optimizer.zero_grad()

        outputs = model(patches)

        loss = criterion(outputs, labels_batch)

        loss.backward()

        optimizer.step()

        train_loss += loss.item()

    model.eval()
    val_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():

        for patches, labels_batch in val_loader:

            patches = patches.to(device)
            labels_batch = labels_batch.to(device)

            outputs = model(patches)

            loss = criterion(outputs, labels_batch)

            val_loss += loss.item()

            _, predicted = torch.max(outputs, 1)

            total += labels_batch.size(0)
            correct += (predicted == labels_batch).sum().item()

    avg_val_loss = val_loss / len(val_loader)
    val_accuracy = 100 * correct / total

    print(
        f"Epoch {epoch+1}/{epochs} | "
        f"Train Loss: {train_loss/len(train_loader):.4f} | "
        f"Val Loss: {avg_val_loss:.4f} | "
        f"Val Acc: {val_accuracy:.2f}%"
    )

    # Save best model
    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss
        torch.save(model.state_dict(), "best_model.pth")
        print("Best model saved!")

!ls /content/drive/MyDrive | grep test

!unzip "/content/drive/MyDrive/test_dataset-20260311T045915Z-1-001.zip" -d /content

!ls /content/test_dataset | head

import torchvision.models as models
import torch.nn as nn

model = models.resnet18(pretrained=False)
model.fc = nn.Linear(512, 3)

model.load_state_dict(torch.load("best_model.pth"))
model = model.to(device)
model.eval()

idx_to_class = {
    0: "Cross",
    1: "Square",
    2: "L-Shaped"
}

from torchvision import transforms

transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

import cv2
import numpy as np

def detect_marker_center(image):

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # threshold bright regions
    _, thresh = cv2.threshold(gray, 200, 255, cv2.THRESH_BINARY)

    contours, _ = cv2.findContours(
        thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
    )

    if len(contours) == 0:
        return None

    # choose largest white region
    largest = max(contours, key=cv2.contourArea)

    M = cv2.moments(largest)

    if M["m00"] == 0:
        return None

    cx = int(M["m10"] / M["m00"])
    cy = int(M["m01"] / M["m00"])

    return cx, cy

import os

test_image_path = "/content/test_dataset/231129_CTD/231129_CTD_GDA94/jg3/DJI_20231129141742_0017.JPG"

img = cv2.imread(test_image_path)

if img is None:
    print(f"Error: Could not load image from {test_image_path}. Please check the path and file integrity.")
else:
    cx, cy = detect_marker_center(img)
    print(cx, cy)

import matplotlib.pyplot as plt

img_copy = img.copy()

cv2.circle(img_copy, (cx,cy), 20, (0,0,255), -1)

plt.imshow(cv2.cvtColor(img_copy, cv2.COLOR_BGR2RGB))
plt.show()

def crop_patch(image, cx, cy, size=224):

    h, w, _ = image.shape
    half = size // 2

    x1 = max(cx - half, 0)
    y1 = max(cy - half, 0)

    x2 = min(cx + half, w)
    y2 = min(cy + half, h)

    patch = image[y1:y2, x1:x2]

    return patch

patch = crop_patch(img, cx, cy)

plt.imshow(cv2.cvtColor(patch, cv2.COLOR_BGR2RGB))
plt.show()

def predict_shape(patch):

    patch = transform(patch)
    patch = patch.unsqueeze(0)
    patch = patch.to(device)

    with torch.no_grad():
        outputs = model(patch)

    _, pred = torch.max(outputs, 1)

    return idx_to_class[pred.item()]

patched_tensor = transform(patch)
patched_tensor = patched_tensor.unsqueeze(0)
patched_tensor = patched_tensor.to(device)

with torch.no_grad():
    outputs = model(patched_tensor)

torch.max(outputs,1)

shape = predict_shape(patch)
print(shape)

predictions = {}
import os

image_paths = []

for root, dirs, files in os.walk("/content/test_dataset"):
    for file in files:
        if file.endswith(".JPG") or file.endswith(".jpg"):
            image_paths.append(os.path.join(root, file))

print("Total test images:", len(image_paths))

for path in image_paths:

    img = cv2.imread(path)

    result = detect_marker_center(img)

    if result is None:
        continue

    cx, cy = result

    patch = crop_patch(img, cx, cy)

    shape = predict_shape(patch)

    key = path.replace("/content/test_dataset/", "")

    predictions[key] = {
        "mark": {
            "x": float(cx),
            "y": float(cy)
        },
        "verified_shape": shape
    }

import json

with open("predictions.json", "w") as f:
    json.dump(predictions, f, indent=4)

print("predictions.json saved")

!ls